header
MarkRemedio/expresswap-frontend pull request #1
Opened 2021-03-01 17:29 UTC by MarkRemedio

2021-03-02 13:53 UTC, litocabornay requested changes
@MarkRemedio can we removed underline during the hover of ExpressSwap link? also the color should be remain or highlighted?

2021-03-02 14:32 UTC, litocabornay commented
@MarkRemedio sorry bro, kani active nga page bah, sa template jud ni siya? pwde raba same sa color sa swap nga word? nya dili ma box highlight? ang word home?
<img width="1080" alt="Screenshot 2021-03-02 at 10 30 08 PM" src="https://user-images.githubusercontent.com/1973910/109663357-f92a0400-7ba6-11eb-915c-986b7bafbbcc.png">

2021-03-05 06:55 UTC, zbads06 approved these changes

2021-03-10 13:34 UTC, litocabornay approved these changes
LGTM!

2021-03-10 13:35 UTC, merged